version: '3.3'

volumes:
  static_value:
  media_value:
  database:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - ./.env
    container_name: foodgram_db 

  backend:
    image: kotbarbarossa/foodgram-project-react-backend:latest
    restart: always
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    container_name: foodgram_backend

  frontend:
    image: kotbarbarossa/foodgram-project-react-frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - frontend
    container_name: foodgram_nginx
